import { describe, it, expect, beforeEach, vi } from 'vitest';
import { screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Routes, Route } from 'react-router-dom';
import { http, HttpResponse } from 'msw';

import ProjectsPage from './ProjectsPage';
import { renderWithRouter } from '@/test/utils';
import { server } from '@/test/msw/server';
import { loginAsUser } from '@/test/helpers/auth.helpers';

// Helper to mock the complex POST search request
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const mockProjectsResponse = (projects: any[], total = projects.length) => {
    server.use(
        http.post('*/projects/searches', () => {
            return HttpResponse.json({
                search_info: { total, page: 1, limit: 10 },
                projects
            });
        })
    );
};

// Dummy project data for testing
const MOCK_PROJECT_1 = {
    project_id: 101,
    project_title: 'Ocean Deep Exploration',
    project_acronym: 'ODE',
    instrument_model: 'UVP5HD',
    ecotaxa_project_name: 'ecotaxa_ode',
    root_folder_path: '/data/ode',
    managers: [{ user_id: 1 }],
    members: [],
    qc_state: 'validated'
};

const MOCK_PROJECT_2 = {
    project_id: 202,
    project_title: 'Coastal Monitoring',
    project_acronym: 'COAST',
    instrument_model: 'UVP6LP',
    ecotaxa_project_name: null,
    root_folder_path: '/data/coast',
    managers: [],
    members: [{ user_id: 1 }],
    qc_state: 'warning'
};

describe('ProjectsPage (Functional)', () => {

    beforeEach(() => {
        loginAsUser();
        vi.clearAllMocks();
    });

    // TC-G1: Initial Data Loading
    it('TC-G1: should load and display projects in the DataGrid', async () => {
        mockProjectsResponse([MOCK_PROJECT_1, MOCK_PROJECT_2]);

        renderWithRouter(
            <Routes>
                <Route path="/projects" element={<ProjectsPage />} />
            </Routes>,
            { route: '/projects' }
        );

        expect(await screen.findByText('Ocean Deep Exploration')).toBeInTheDocument();
        expect(screen.getByText('Coastal Monitoring')).toBeInTheDocument();

        const chipManager = screen.getAllByText('Manager');
        expect(chipManager.length).toBeGreaterThan(0);

        expect(screen.getByText('Not linked')).toBeInTheDocument();
    });

    // TC-G2: Error Handling
    it('TC-G2: should display an error alert if the API fails', async () => {
        // Force API failure
        server.use(
            http.post('*/projects/searches', () => {
                // Our HTTP client intercepts non-2xx responses and throws an Error
                // whose message is typically "HTTP Error: 500" if no JSON body is provided.
                // We test against this actual observed behavior.
                return new HttpResponse(null, { status: 500 });
            })
        );

        renderWithRouter(<ProjectsPage />, { route: '/projects' });

        const alert = await screen.findByRole('alert');
        expect(within(alert).getByText(/Failed to load projects from server/i)).toBeInTheDocument();

        // Check for the specific error message generated by the HTTP client
        expect(within(alert).getByText(/HTTP Error: 500/i)).toBeInTheDocument();
    });

    // TC-G3: Filtering & Searching (UI State)
    it('TC-G3: should update UI when filters and search attributes are changed', async () => {
        const user = userEvent.setup();
        mockProjectsResponse([]);

        renderWithRouter(<ProjectsPage />, { route: '/projects' });

        const searchInput = await screen.findByPlaceholderText('Search...');
        await user.type(searchInput, 'Tara');
        expect(searchInput).toHaveValue('Tara');

        // The default text is "All My Projects" based on the Hook's initial state
        const filterButton = screen.getByRole('button', { name: 'All My Projects' });
        await user.click(filterButton);

        const validatedMenuItem = screen.getByRole('menuitem', { name: 'Validated QC' });
        await user.click(validatedMenuItem);

        expect(screen.getByRole('button', { name: 'Filter: Validated' })).toBeInTheDocument();
    }, 15000);

    // TC-G4: Row Selection & Explore Navigation
    it('TC-G4: should allow row selection and navigate to explore with selected IDs', async () => {
        const user = userEvent.setup();
        mockProjectsResponse([MOCK_PROJECT_1, MOCK_PROJECT_2]);

        renderWithRouter(
            <Routes>
                <Route path="/projects" element={<ProjectsPage />} />
                <Route path="/explore" element={<h1>Explore Page Mock</h1>} />
            </Routes>,
            { route: '/projects' }
        );

        await screen.findByText('Ocean Deep Exploration');

        const rowCheckboxes = screen.getAllByLabelText(/Select row/i);
        await user.click(rowCheckboxes[0]);

        expect(screen.getByText('1 items selected')).toBeInTheDocument();

        const exploreButton = screen.getByRole('button', { name: /EXPLORE SELECTION/i });
        await user.click(exploreButton);

        expect(await screen.findByText('Explore Page Mock')).toBeInTheDocument();
    }, 15000);

    // TC-G5: Row Click Navigation
    it('TC-G5: should navigate to project details when a row is clicked', async () => {
        const user = userEvent.setup();
        mockProjectsResponse([MOCK_PROJECT_1]);

        renderWithRouter(
            <Routes>
                <Route path="/projects" element={<ProjectsPage />} />
                <Route path="/projects/:id/:tabName?" element={<h1>Project Details Mock</h1>} />
            </Routes>,
            { route: '/projects' }
        );

        const projectCell = await screen.findByText('Ocean Deep Exploration');

        await user.click(projectCell);

        expect(await screen.findByText('Project Details Mock')).toBeInTheDocument();
    }, 15000);

    // TC-G4b: Delete a managed project from the selection bar
    it('TC-G4b: should delete the selected managed project after confirmation', async () => {
        const user = userEvent.setup();
        const deletedIds: string[] = [];

        mockProjectsResponse([MOCK_PROJECT_1, MOCK_PROJECT_2]);
        server.use(
            http.delete('*/projects/:projectId/', ({ params }) => {
                deletedIds.push(String(params.projectId));
                return HttpResponse.json({ message: 'deleted' });
            })
        );
        const confirmSpy = vi.spyOn(window, 'confirm').mockReturnValue(true);

        renderWithRouter(<ProjectsPage />, { route: '/projects' });

        await screen.findByText('Ocean Deep Exploration');

        // MOCK_PROJECT_1 is managed by the logged-in user (user_id 1).
        const rowCheckboxes = screen.getAllByLabelText(/Select row/i);
        await user.click(rowCheckboxes[0]);

        const deleteButton = screen.getByRole('button', { name: /DELETE/i });
        expect(deleteButton).toBeEnabled();

        await user.click(deleteButton);

        expect(confirmSpy).toHaveBeenCalled();
        expect(await screen.findByText(/Project\(s\) deleted\./i)).toBeInTheDocument();
        expect(deletedIds).toEqual(['101']);

        confirmSpy.mockRestore();
    }, 15000);

    // TC-G4c: Delete stays disabled for a project the user is only a member of
    it('TC-G4c: should keep DELETE disabled when the selection is not managed by the user', async () => {
        const user = userEvent.setup();
        mockProjectsResponse([MOCK_PROJECT_1, MOCK_PROJECT_2]);

        renderWithRouter(<ProjectsPage />, { route: '/projects' });

        await screen.findByText('Coastal Monitoring');

        // Nothing selected yet: the action is unavailable.
        expect(screen.getByRole('button', { name: /DELETE/i })).toBeDisabled();

        // MOCK_PROJECT_2 only lists the user as a member.
        const rowCheckboxes = screen.getAllByLabelText(/Select row/i);
        await user.click(rowCheckboxes[1]);

        expect(screen.getByText('1 items selected')).toBeInTheDocument();
        expect(screen.getByRole('button', { name: /DELETE/i })).toBeDisabled();
    }, 15000);

    // TC-G6: Projects Pagination & Query Sync
    it('TC-G6: should request next page and render new rows when pagination changes', async () => {
        const user = userEvent.setup();
        const requestedPages: string[] = [];
        const requestedSortValues: string[] = [];

        server.use(
            http.post('*/projects/searches*', ({ request }) => {
                const url = new URL(request.url);
                const page = url.searchParams.get('page') ?? '1';
                const sortBy = url.searchParams.get('sort_by') ?? '';
                requestedPages.push(page);
                requestedSortValues.push(sortBy);

                if (page === '2') {
                    return HttpResponse.json({
                        search_info: { total: 15, page: 2, limit: 10 },
                        projects: [{
                            ...MOCK_PROJECT_2,
                            project_id: 303,
                            project_title: 'Page Two Project'
                        }]
                    });
                }

                return HttpResponse.json({
                    search_info: { total: 15, page: 1, limit: 10 },
                    projects: [MOCK_PROJECT_1]
                });
            })
        );

        renderWithRouter(<ProjectsPage />, { route: '/projects' });

        expect(await screen.findByText('Ocean Deep Exploration')).toBeInTheDocument();

        const nextPageButton = screen.getByRole('button', { name: /Go to next page/i });
        await user.click(nextPageButton);

        expect(await screen.findByText('Page Two Project')).toBeInTheDocument();
        expect(requestedPages).toContain('1');
        expect(requestedPages).toContain('2');
        expect(requestedSortValues.every((value) => value === 'desc(project_id)')).toBe(true);
    }, 15000);

});